# Generated by Django 4.2 on 2023-05-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_onboarding', '0002_alter_selleronboarding_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleronboarding',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
